### PR TITLE
Added the functionality for the visitors' sequence diagram

### PR DESCRIPTION
**Pull request by vincentdelitz**

### CODE REVIEW

**Comment by demirdagemir** [comment]
Are you sure you pushed everything? When I go to `/stage` I get 404 errors, as well as the homework example etc.

**Comment by demirdagemir** [comment]
@vincentdelitz  I think we should have the "servers" also hosted on the repo. Probably you changed things there and since I don't have it I get 404 errors.

**Comment by vincentdelitz** [comment]
@demirdagemir the homework example doesn't hold anymore, since it is a different database. So forget about that ;)

**Comment by vincentdelitz** [comment]
Regarding the /stage problem: for me it worked perfectly. Do you have the right configuration in config.java?

**Comment by demirdagemir** [comment]
I do, and I don't think it's a DB problem. I get 404 errors. The link must be pointing to the wrong file

**Comment by vincentdelitz** [comment]
That's really strange. How did you test it? Did you download my files and try it ?

**Comment by vincentdelitz** [comment]
Maybe someone else could test and review it as well?

**Comment by dani2914** [comment]
yeah i will test it tonight.


On 15 Jul 2017, at 11:25 AM, vincentdelitz <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe someone else could test and review it as well?

-

**Comment by MilenaZurmuehl** [comment]
@vincentdelitz I checked it and it works!! :)

**Comment by MilenaZurmuehl** [comment]
Maybe someone can check the organiser branch?

**Comment by vincentdelitz** [comment]
@MilenaZurmuehl if you think that your organiser branch is done, then create a pull request (same as this one here) ;)

**Review by MilenaZurmuehl — APPROVED** [review]
Script works

**Pull request merged**
